name: Thing to run on tags

on:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_REF
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo $TAG_NAME
